### ISSUE TITLE
French version of MST-FRE isn't French 

### ISSUE THREAD

**Issue by graybeal** [ncbo/umls2rdf#32]
Looking over the UMLS2RDF config file (https://github.com/ncbo/umls2rdf/blob/master/umls.conf) I noticed something looked amiss at the end. The same acronym was used for two ontologies, the Minimal Standard Terminology of Digestive Endoscopy, and its French counterpart. When I checked the actual ontologies at 
* http://bioportal.bioontology.org/ontologies/MSTDE and
* http://bioportal.bioontology.org/ontologies/MSTDE-FRE
I saw they appeared the same.  

Checking in SIFR, the same ontology appears in actual French, as expected. 

I conclude there is (and has always been) a bug in the UMLS2RDF config file, that it is loading MTHMST instead of MTHMSTFRE.

**Comment by graybeal** [comment]
I went ahead and just made this change in master, because it is So Simple. Would someone have a look to confirm they believe it is correct? (And tell me what I should have done to make the change properly, if not that. We could always revert so I could do it right...)

**Comment by jvendetti** [comment]
I don't see any issue with this commit (be8cc0da426e64f64de5f75264bbf48b2b5f9b87).

However, @alexskr has overseen the UMLS import process since Manuel's departure. Perhaps he'd like the opportunity to weigh in here.

**Comment by jonquet** [comment]
A few corrections: 

1. MSTDE does not exist. It's not a valid UMLS source: 
https://www.nlm.nih.gov/research/umls/sourcereleasedocs/index.html
Therefore: 
http://bioportal.bioontology.org/ontologies/MSTDE
should be rename MTHMST and populate with the ttl files from the UMLS MTHMST source

2. Consequently MSTDE-FRE does not exist also. 
The french version is indeed named MTHMSTFRE
My recommendation would be to remove 
http://bioportal.bioontology.org/ontologies/MSTDE-FRE
from NCBO BioPortal because we provide it in SIFR BioPortal with an explicit metadata link to NCBO BioPortal's english version: 
http://bioportal.lirmm.fr/ontologies/MTHMSTFRE
and because those french resources (sometimes views, sometime not) aliment the confusion about how multiligual resources are hosted in the NCBO BioPortal

3. I would generalize point #2 to any other French only terminologies in the NCBO BioPortal.

**Comment by alexskr** [comment]
I took @jonquet 3rd recommendation and made MSTDE-FRE a view of MSTDE ontology.
